[package]
name = "demo-rust"
version = "0.1.0"
authors = ["Anton Pirker <anton@ignaz.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
